### ISSUE TITLE
What does the `decrease` param mean in ConstructRemoveAuthorizedParty func

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-lib#53]
Can you elaborate on what `decrease` does? Does it decrease the signing thresholds for a msig?

For instance there are 2 signers for a 1/1 msig actor. When I remove 1 signer and set `decrease` to false, I assuming the signing thresholds remain at 1/1?

What happened when there are more signers say I have 4 signers and I have a 3/4 msig actor. When I remove 1 signer and set `decrease` to true, does it reduce the thresholds to 2/3?

**Comment by arajasek** [comment]
Assuming this gets piped into the multisig actor as the `decrease` param in `RemoveSignerParams`, then, yes, this boolean indicates whether the signing threshold should be decreased.

I don't know what the `x/y` notation means when talking about multisigs, but, here's some examples, starting with your scenarios:

- If there are 5 signers for a msig with threshold set to 4, and you remove a signer with `decrease = false`, the threshold will stay at 4
- If there are 5 signers for a msig with threshold set to 4, and you remove a signer with `decrease = true`, the threshold will fall to 3
- If there are 5 signers for a msig with threshold set to 5, and you remove a signer with `decrease = false`, the remove operation will fail, since this was put the multisig in a useless state. Decrease must be set to true.
- If there are 5 signers for a msig with threshold set to 1, and you remove a signer with `decrease = true`, the remove operation will fail, since this was put the multisig in an insecure state (zero thresholds). Decrease must be set to false.

**Comment by qiwu7** [comment]
Thank you! closing
